export { default as drm } from './stages/drm.ts'
export { default as metadata } from './stages/metadata.ts'
export { default as persist } from './stages/persist.ts'
export { default as person } from './stages/person.ts'
export { default as thumbnail } from './stages/thumbnail.ts'
export { default as title } from './stages/title.ts'
