/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A [BCP 47 language tag](https://en.wikipedia.org/wiki/IETF_language_tag#List_of_major_primary_language_subtags) used throughout the application.
 */
export type ApplicationLocale = string;
/**
 * The level of detail recorded by the logger.
 */
export type LoggingLevel = "debug" | "info" | "warn" | "error";
/**
 * The number of days to retain log files.
 */
export type LoggingRetentionDays = number;
/**
 * The file system path where application data is stored. This makes Xon highly portable across systems.
 */
export type ApplicationDataPath = string;
/**
 * The file system path where application databases are stored.
 */
export type ApplicationDatabasePath = string;
/**
 * The file system path where application cache is stored.
 */
export type ApplicationCachePath = string;
/**
 * The amount of local disk space to use for storing cache files.
 */
export type ApplicationCacheQuota = number;
/**
 * The file system path where application logs are stored.
 */
export type ApplicationLogsPath = string;
/**
 * The file system path where application plugins are stored.
 */
export type ApplicationPluginsPath = string;
export type ServerPort = number;
export type HTTPPort = number;
export type HTTPSPort = number;
/**
 * The file system path where SSL certificates are stored.
 */
export type SSLCertificatesPath = string;
export type EnableRemoteAccess = boolean;
export type EnableCORS = boolean;
export type CORSAllowedOrigins = string[];
export type SessionTTLDays = number;
/**
 * The number of days after which the session expiration is updated.
 */
export type SessionUpdateAge = number;
/**
 * By default, whenever the session is used and the updateAge is reached, the session expiration is updated. This setting disables that functionality.
 */
export type DisableSessionRefresh = boolean;
/**
 * By default, Xon does not require an account to login. This makes Xon very easy to use, especially for people that don't need the additional security features. If, however, you want to require accounts, simply turn this off.
 */
export type AllowAnonymousLogins = boolean;

export interface XonConfigSchema {
  "app.locale": ApplicationLocale;
  "log.level": LoggingLevel;
  "log.retentionDays": LoggingRetentionDays;
  "appdata.path": ApplicationDataPath;
  "appdata.dbPath": ApplicationDatabasePath;
  "appdata.cachePath": ApplicationCachePath;
  "appdata.cacheQuota": ApplicationCacheQuota;
  "appdata.logsPath": ApplicationLogsPath;
  "appdata.pluginsPath": ApplicationPluginsPath;
  "server.port"?: ServerPort;
  "network.httpPort": HTTPPort;
  "network.httpsPort"?: HTTPSPort;
  "network.sslPath"?: SSLCertificatesPath;
  "network.remoteEnabled": EnableRemoteAccess;
  "network.security.corsEnabled": EnableCORS;
  "network.security.corsAllowedOrigins": CORSAllowedOrigins;
  "session.ttlDays": SessionTTLDays;
  "session.updateAge": SessionUpdateAge;
  "session.disableSessionRefresh": DisableSessionRefresh;
  "session.enableAnonymousLogins": AllowAnonymousLogins;
}
