import {
  FolderAdd20Regular as AddLibraryIcon,
  DrawerAddRegular as AddToIcon,
  TextBulletListAddRegular as AddToPlaylistIcon,
  Dismiss16Regular as CloseIcon,
  DeleteDismiss20Regular as DeleteIcon,
  ArrowDownload16Regular as DownloadIcon,
  DocumentEdit16Regular as EditIcon,
  LinkEdit16Regular as FixMatchIcon,
  Folder16Regular as FolderIcon,
  ImageEdit16Regular as ImageEditIcon,
  MoreVertical24Regular as MoreIcon,
  TabDesktop16Regular as OpenIcon,
  TabDesktopCopyRegular as OpenInNewTabIcon,
  ArrowSync16Regular as RefreshIcon,
  FolderSearch16Regular as ScanIcon,
} from '@fluentui/react-icons'

export default {
  RefreshMetadata: RefreshIcon,
  EditImages: ImageEditIcon,
  Download: DownloadIcon,
  Delete: DeleteIcon,
  FixMatch: FixMatchIcon,
  Edit: EditIcon,
  AddTo: AddToIcon,
  Scan: ScanIcon,
  More: MoreIcon,
  Folder: FolderIcon,
  AddLibrary: AddLibraryIcon,
  Open: OpenIcon,
  OpenInNewTab: OpenInNewTabIcon,
  AddToPlaylist: AddToPlaylistIcon,
  Close: CloseIcon,
}
